### ISSUE TITLE
Improve error checking during server start

### ISSUE THREAD

**Issue by ChristianMurphy** [promisasu/Portal#307]
**What did you do?**
I added an extra comma in the configuration file.
``` json
{
  "dashboard": {
    "hostname": "localhost",
    "port": 3000,
  }
}
```
**What did you expect to happen?**
A message with location, and type of error to be displayed.

**What actually happened?**
``` sh
module.js:433
    throw err;
    ^

SyntaxError: /home/developer/Projects/Portal/config.json: Unexpected token }
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:430:27)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/developer/Projects/Portal/task/start-api.js:10:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by ChristianMurphy** [comment]
Resolved by #309
